### ISSUE TITLE
关于流程的问题

### ISSUE THREAD

**Issue by qq1176914912** [q1006608006/sm2-duplicate-sign#1]
您好，我注意到您里面的复杂模式与《[基于 SM2 的双方共同签名协议及其应用（苏吟雪 田海博）](http://cjc.ict.ac.cn/online/onlinepaper/009_syx-2020415163110.pdf)》中的共同签名生成协议过程类似：
![image](https://github.com/user-attachments/assets/722e8f21-ff34-46b1-98b4-8ba7dafb088e)
但复杂模式中的第5步 和过程有些不同，按照流程图中的步骤，s'也就是您步骤中的S_不应该是由请求方（Alice）计算并返回给的参与方的么，但是在您的这个过程里面确是参与方返回要素s_,难道说S_不是对应文章中的S'  ?

**Comment by q1006608006** [comment]
s1是Bob，s2是Alice。至于为什么这里是Bob直接给出的签名，因为最后一步中 s=t-r，R'(xa,xb) = RA+RB，r=H(Z_alice||M) + xa mod q，其中只有Z_alice是基于Alice的ID，其他都是双方已知参数，在ID都为默认值(1234567812345678)的情况下，或者已知对方ID的情况下，可以直接由Bob给出签名。

**Comment by q1006608006** [comment]
通过你的提醒，我发现整个模式确实流程上有很多不合适的地方，尽管少了交互步骤，但是没有实际的应用场景。尽管有些参数是公开的，但确实不应该混淆使用者，我会找时间进行调整，感谢

**Comment by qq1176914912** [comment]
> 通过你的提醒，我发现整个模式确实流程上有很多不合适的地方，尽管少了交互步骤，但是没有实际的应用场景。尽管有些参数是公开的，但确实不应该混淆使用者，我会找时间进行调整，感谢

感谢您的回复，如果您调整好了，麻烦回复一下我，感谢！
